version: '3.7'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${USERNAME_DB_DOCKER}
      POSTGRES_PASSWORD: ${PASSWORD_DB_DOCKER}
    volumes:
      - ./infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql    
    networks:
      - dbnet
    
  bakend:
    image: app/appmarks
    container_name: bakend
    ports:
      - 4567:4567
    depends_on:
      - db
    networks:
      - dbnet
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - dbnet

networks:
  dbnet:
    driver: bridge