version: '3.7'

services:
  db:
    image: postgres
    container_name: servicedb
    env_file:
      - ./envs/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d appmarks" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - dbnet
    
  bakend:
    image: app/appmarks
    container_name: bakend
    ports:
      - 4567:4567
    env_file:
      - ./envs/app.env    
    depends_on:
      - db
    volumes:
      - imgs:/node_app/imgs
    networks:
      - dbnet

volumes:
  postgres_data:  
  imgs:

networks:
  dbnet:
    driver: bridge