version: '3.7'

services:
  db:
    image: postgres
    container_name: ${HOST_DOCKER}
    environment:
      POSTGRES_USER: ${USERNAME_DB_DOCKER}
      POSTGRES_PASSWORD: ${PASSWORD_DB_DOCKER}
    volumes:
      - ./infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql    
    networks:
      - dbnet
    
  bakend:
    image: app/appmarks
    container_name: bakend
    restart: always
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    networks:
      - dbnet
  
  

networks:
  dbnet:
    driver: bridge