version: '3.7'

services:
  db:
    image: postgres
    container_name: servicedb
    env_file:
      - ./envs/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dbnet
    
  bakend:
    image: app/appmarks
    container_name: bakend
    ports:
      - 4567:4567
    env_file:
      - ./envs/app.env    
    depends_on:
      - db
    networks:
      - dbnet

volumes:
  postgres_data:  

networks:
  dbnet:
    driver: bridge